/*
 * generated by Xtext
 */
package at.ac.tuwien.big.momot.lang


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MOMoTStandaloneSetup extends MOMoTStandaloneSetupGenerated {

	def static void doSetup() {
		new MOMoTStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
