/*
 * generated by Xtext
 */
package at.ac.tuwien.big.momot.lang


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MOMoTRuntimeModule extends AbstractMOMoTRuntimeModule {
   override Class<? extends org.eclipse.xtext.xbase.scoping.batch.IBatchScopeProvider> bindIBatchScopeProvider() {
      return org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider
   }
}
